//! Generate the JSON wire vocabulary from its Rust/serde authority.
use ts_rs::TS;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let config = ts_rs::Config::default().with_large_int("number");
    let mut output = String::from(
        "// Generated by cargo run -p denia-core --features bindings --example bindings.\n// Do not edit: Rust/serde owns these wire types.\n\n",
    );
    output.push_str("export ");
    output.push_str(&denia_core::config::LlmCallConfig::decl(&config));
    output.push_str("\n\n");
    output.push_str("export ");
    output.push_str(&denia_core::config::ModelSelection::decl(&config));
    output.push_str("\n\n");
    output.push_str("export ");
    output.push_str(&denia_core::error::LlmFailure::decl(&config));
    output.push_str("\n\n");
    output.push_str("export ");
    output.push_str(&denia_core::message::ChatRole::decl(&config));
    output.push_str("\n\n");
    output.push_str("export ");
    output.push_str(&denia_core::message::ToolCallRef::decl(&config));
    output.push_str("\n\n");
    output.push_str("export ");
    output.push_str(&denia_core::message::ImageData::decl(&config));
    output.push_str("\n\n");
    output.push_str("export ");
    output.push_str(&denia_core::message::ChatMessage::decl(&config));
    output.push_str("\n\n");
    output.push_str("export ");
    output.push_str(&denia_core::preset::PresetTrust::decl(&config));
    output.push_str("\n\n");
    output.push_str("export ");
    output.push_str(&denia_core::preset::PresetFeatures::decl(&config));
    output.push_str("\n\n");
    output.push_str("export ");
    output.push_str(&denia_core::preset::AgentPreset::decl(&config));
    output.push_str("\n\n");
    output.push_str("export ");
    output.push_str(&denia_core::preset::PresetSpec::decl(&config));
    output.push_str("\n\n");
    output.push_str("export ");
    output.push_str(&denia_core::session::SessionHeader::decl(&config));
    output.push_str("\n\n");
    output.push_str("export ");
    output.push_str(&denia_core::session::SubagentDescriptor::decl(&config));
    output.push_str("\n\n");
    output.push_str("export ");
    output.push_str(&denia_core::session::SubagentProfileRef::decl(&config));
    output.push_str("\n\n");
    output.push_str("export ");
    output.push_str(&denia_core::session::SubagentForkProjection::decl(&config));
    output.push_str("\n\n");
    output.push_str("export ");
    output.push_str(&denia_core::session::LegacySubagentInfo::decl(&config));
    output.push_str("\n\n");
    output.push_str("export ");
    output.push_str(&denia_core::subagent::ProfileSource::decl(&config));
    output.push_str("\n\n");
    output.push_str("export ");
    output.push_str(&denia_core::subagent::ToolSelection::decl(&config));
    output.push_str("\n\n");
    output.push_str("export ");
    output.push_str(&denia_core::subagent::ModelChoice::decl(&config));
    output.push_str("\n\n");
    output.push_str("export ");
    output.push_str(&denia_core::subagent::PermissionCeiling::decl(&config));
    output.push_str("\n\n");
    output.push_str("export ");
    output.push_str(&denia_core::subagent::ProfileColor::decl(&config));
    output.push_str("\n\n");
    output.push_str("export ");
    output.push_str(&denia_core::subagent::ProfileWriteScope::decl(&config));
    output.push_str("\n\n");
    output.push_str("export ");
    output.push_str(&denia_core::subagent::SubagentProfile::decl(&config));
    output.push_str("\n\n");
    output.push_str("export ");
    output.push_str(&denia_core::subagent::SubagentInlineSpec::decl(&config));
    output.push_str("\n\n");
    output.push_str("export ");
    output.push_str(&denia_core::subagent::ProfileDiagnostic::decl(&config));
    output.push_str("\n\n");
    output.push_str("export ");
    output.push_str(&denia_core::subagent::SubagentProfileView::decl(&config));
    output.push_str("\n\n");
    output.push_str("export ");
    output.push_str(&denia_core::subagent::SubagentCatalogEntry::decl(&config));
    output.push_str("\n\n");
    output.push_str("export ");
    output.push_str(&denia_core::session::SessionHeaderKind::decl(&config));
    output.push_str("\n\n");
    output.push_str("export ");
    output.push_str(&denia_core::session::TurnEndReason::decl(&config));
    output.push_str("\n\n");
    output.push_str("export ");
    output.push_str(&denia_core::session::AbortCause::decl(&config));
    output.push_str("\n\n");
    output.push_str("export ");
    output.push_str(&denia_core::session::PermissionMode::decl(&config));
    output.push_str("\n\n");
    output.push_str("export ");
    output.push_str(&denia_core::session::ApprovalPolicy::decl(&config));
    output.push_str("\n\n");
    output.push_str("export ");
    output.push_str(&denia_core::session::ApprovalOutcome::decl(&config));
    output.push_str("\n\n");
    output.push_str("export ");
    output.push_str(&denia_core::session::PlanReviewDecision::decl(&config));
    output.push_str("\n\n");
    output.push_str("export ");
    output.push_str(&denia_core::session::AskOption::decl(&config));
    output.push_str("\n\n");
    output.push_str("export ");
    output.push_str(&denia_core::session::AskQuestion::decl(&config));
    output.push_str("\n\n");
    output.push_str("export ");
    output.push_str(&denia_core::session::AskAnswer::decl(&config));
    output.push_str("\n\n");
    output.push_str("export ");
    output.push_str(&denia_core::session::AskOutcome::decl(&config));
    output.push_str("\n\n");
    output.push_str("export ");
    output.push_str(&denia_core::session::AskResolution::decl(&config));
    output.push_str("\n\n");
    output.push_str("export ");
    output.push_str(&denia_core::session::TodoItem::decl(&config));
    output.push_str("\n\n");
    output.push_str("export ");
    output.push_str(&denia_core::session::TodoStatus::decl(&config));
    output.push_str("\n\n");
    output.push_str("export ");
    output.push_str(&denia_core::session::GoalStatus::decl(&config));
    output.push_str("\n\n");
    output.push_str("export ");
    output.push_str(&denia_core::session::GoalState::decl(&config));
    output.push_str("\n\n");
    output.push_str("export ");
    output.push_str(&denia_core::session::GoalOp::decl(&config));
    output.push_str("\n\n");
    // 任务账本:`task` 事件负载(`SessionEvent::Task`)与只读任务视图共用的
    // 词汇。`TaskOp` 不在别处出现时会被 `SessionEvent` 引用,而引用不会自带
    // 定义 —— 少一条就是一份编译不过的绑定。名单顺序跟随 `task.rs`。
    for decl in [
        denia_core::task::TaskId::decl(&config),
        denia_core::task::RevisionId::decl(&config),
        denia_core::task::EvidenceId::decl(&config),
        denia_core::task::RequirementId::decl(&config),
        denia_core::task::NoteId::decl(&config),
        denia_core::task::SourceRef::decl(&config),
        denia_core::task::RequirementKind::decl(&config),
        denia_core::task::RequirementClaim::decl(&config),
        denia_core::task::Requirement::decl(&config),
        denia_core::task::RevisionRecord::decl(&config),
        denia_core::task::FactCitation::decl(&config),
        denia_core::task::NoteClaim::decl(&config),
        denia_core::task::Fact::decl(&config),
        denia_core::task::Assumption::decl(&config),
        denia_core::task::FailedAttempt::decl(&config),
        denia_core::task::OpenQuestion::decl(&config),
        denia_core::task::FileFingerprint::decl(&config),
        denia_core::task::EvidenceSource::decl(&config),
        denia_core::task::Evidence::decl(&config),
        denia_core::task::CheckRun::decl(&config),
        denia_core::task::ValidationVerdict::decl(&config),
        denia_core::task::ValidationResult::decl(&config),
        denia_core::task::TaskChange::decl(&config),
        denia_core::task::LedgerOverflow::decl(&config),
        denia_core::task::TaskStatus::decl(&config),
        denia_core::task::TaskOutcome::decl(&config),
        denia_core::task::StaleReason::decl(&config),
        denia_core::task::VerificationState::decl(&config),
        denia_core::task::TaskState::decl(&config),
        denia_core::task::TaskOp::decl(&config),
    ] {
        output.push_str("export ");
        output.push_str(&decl);
        output.push_str("\n\n");
    }
    output.push_str("export ");
    output.push_str(&denia_core::session::RequestHeaderReason::decl(&config));
    output.push_str("\n\n");
    output.push_str("export ");
    output.push_str(&denia_core::session::RequestHeaderSnapshot::decl(&config));
    output.push_str("\n\n");
    output.push_str("export ");
    output.push_str(&denia_core::session::ToolFailureIdentity::decl(&config));
    output.push_str("\n\n");
    output.push_str("export ");
    output.push_str(&denia_core::session::TruncationInfo::decl(&config));
    output.push_str("\n\n");
    output.push_str("export ");
    output.push_str(&denia_core::session::SessionEvent::decl(&config));
    output.push_str("\n\n");
    output.push_str("export ");
    output.push_str(&denia_core::session::SessionEnvelope::decl(&config));
    output.push_str("\n\n");
    output.push_str("export ");
    output.push_str(&denia_core::stream::BlockType::decl(&config));
    output.push_str("\n\n");
    output.push_str("export ");
    output.push_str(&denia_core::stream::ContentBlock::decl(&config));
    output.push_str("\n\n");
    output.push_str("export ");
    output.push_str(&denia_core::stream::ReasoningReplay::decl(&config));
    output.push_str("\n\n");
    output.push_str("export ");
    output.push_str(&denia_core::stream::TokenUsage::decl(&config));
    output.push_str("\n\n");
    output.push_str("export ");
    output.push_str(&denia_core::stream::FinishReason::decl(&config));
    output.push_str("\n\n");
    output.push_str("export ");
    output.push_str(&denia_core::stream::StreamChunk::decl(&config));
    output.push_str("\n\n");
    output.push_str("export ");
    output.push_str(&denia_core::tool::ToolSchema::decl(&config));
    output.push_str("\n\n");
    let path =
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../web/src/generated/core.ts");
    if std::env::args().any(|arg| arg == "--check") {
        if std::fs::read_to_string(&path)? != output {
            return Err("wire types are stale; run the bindings generator".into());
        }
    } else {
        std::fs::create_dir_all(path.parent().ok_or("missing output directory")?)?;
        std::fs::write(path, output)?;
    }
    Ok(())
}
